#!/bin/bash

yum -y install dhcp  &>/dev/null

cat > /etc/dhcp/dhcpd.conf >>EOF
    default-lease-time 600;
    max-lease-time 7200;
    log-facility local7;
    subnet $dhcp_ns netmask $dhcp_netmask {
        range $dhcp_range_mix $dhcp_range_max;
        next-server $ip_addr;
        filename "$pxelinux";
    }
EOF

start_enable_service dhcp